name: GitHub Snake
on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight
  push:
    branches:
      - main # replace with your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: dark  # optional: dark, light, or colorful
