name: GitHub Snake
on:
  schedule:
    - cron: '0 0 * * *' # daily
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: dark
          file: snake.svg  # output file in root

      - name: Commit and push snake
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update GitHub Snake"
          git push
